In [2]:
import numpy as np

In [33]:
a = np.random.randint(1,10,(2,3,4))
print(a)
for i in range(len(a)):
    l = 0
    for j in range(len(a[0])):
        for k in range(len(a[0,0])):
            a[i,j,k] = l
            l+=1
print(a.dtype)

[[[2 3 2 4]
  [3 5 2 9]
  [6 5 8 9]]

 [[9 1 6 6]
  [7 1 1 5]
  [9 2 8 2]]]
int32


In [34]:
b = np.arange(10)
print(b)
print(b[4:7])

[0 1 2 3 4 5 6 7 8 9]
[4 5 6]


In [38]:
import re
txt = "The rain In Spain"
#Find all lower case characters alphabetically between "a" and
x = re.findall("[A-Ma-m]", txt)
print(x)

['h', 'e', 'a', 'i', 'I', 'a', 'i']


In [45]:
import re
txt = "That will be 59 dollars"
#Find all digit characters:
x = re.findall("\d", txt)
print(x)

['5', '9']


In [57]:
import re
txt = "hello hexxxo hevvvvo heo planet"
#Search for a sequence that starts with "he", followed by two
x = re.findall("he.+o", txt)
print(x)

['hello hexxxo hevvvvo heo']


In [61]:
import re
txt = "The rain in Spain"
#Check if "ain" is present at the beginning of a WORD:
x = re.findall(r"ain\b", txt)
print(x)
if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['ain', 'ain']
Yes, there is at least one match!


In [62]:
import re
txt = "The rain in Spain"
#Return a match at every white-space character:
x = re.findall("\s", txt)
print(x)
if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[' ', ' ', ' ']
Yes, there is at least one match!
